### PR TITLE
waypoint_updater_full

### PR DESCRIPTION
**Pull request by MikeBMW**
I just finished the first version of waypoint updater full, and it runs well in my computer.

### CODE REVIEW

**Comment by wAuner** [comment]
hey mike, could you please comment your code more and write docstrings? As an example you can see the other methods I wrote

**Comment by wAuner** [comment]
also please describe exactly what you‘ve done. I see that there are still TODOs in the code and undefined functions.

**Comment by adai183** [comment]
Hi Mike!
I have another question. How did yo test this? 
Right now  `/traffic_waypoint`  is not publishing any waypoints for upcoming red lights. I will finish a simplified implementation of `tf_detector` early next week. So we can test  `waypoint_updater_full` in the simulator.

**Comment by MikeBMW** [comment]
Ok, I will write more comment. But where is the examples?
I didn't test by /traffic_waypoint, I only test by original waypoint, the car can't see traffic light, there is no stopping.

**Comment by adai183** [comment]
> I didn't test by /traffic_waypoint, I only test by original waypoint, the car can't see traffic light, there is no stopping.

There seems to be a little misunderstanding. `waypoint_updater_full` is supposed to incorporate  traffic light data into the waypoint updater node.

**Comment by MikeBMW** [comment]
I mean that I expect the testing to incorporate traffic light data into the waypoint updater node. The code of waypoint updater node should run well if there is traffic light.

**Comment by adai183** [comment]
ok. We will be able to test this soon.

**Comment by wAuner** [comment]
I close this PR. If you're ready, you can create a new one.

**Pull request closed without merging**
